repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: yarn lint
        language: system
        pass_filenames: false
        priority: 1
      - id: typecheck
        name: typecheck
        entry: yarn typecheck
        language: system
        pass_filenames: false
        priority: 1
      - id: commitlint
        name: commitlint
        entry: yarn commitlint --edit
        language: system
        stages: [commit-msg]
